# Version 0.1.1 [Jul.2023, TF]
name: CallPublicVistronRepoChecks

on:
  # Trigger the workflow on push,
  push:
    # Restrict to pushes on main and master
    branches:
      - master
      - main

  # Trigger the workflow on pull request,
  pull_request:

  # allow for manual start of the test
  workflow_dispatch:
  
jobs:
  R:
    uses: vistron-gmbh/Vistron.GitHub.Actions/.github/workflows/PublicVistronRepoChecks.yml@main
    secrets: inherit
